### ISSUE TITLE
Pomodoro technique

### ISSUE THREAD

**Issue by rodrigoelp** [traversals/luxaforus#16]
Given the base application Luxafor has the Pomodoro Technique, I would like this feature to be included with a twist.

Just to be clear:

### Pomodoro technique
The pomodoro technique has sets of focused work and breaks to help you focus. The technique tells you to have four sets of focused time (25 minutes) followed by a short break (5 minutes) with the fourth break to be a long break of 15 to 30 minutes.

### What I would like?
Initially, the pomodoro technique to be implemented.

### Useful addition
Something the pomodoro technique does not provide (especially when somebody is approaching to interrupt you) is a way to communicate to somebody when your break is approaching (or if you need to queue up a long break before the set of four is done.

The addition consists on:
- Including a button to the pomodoro, to queue a long break instead of a short break without having to interrupt your flow.
- An indication of progress. This can be achieved by having one of the front LED (1 to 3) pulsing or having the back LEDs lighting up for others to see how far are you into the Pomodoro. For instance, turn on the LED 4 after the first 7 minutes, turn on LED 5 after another 7 minutes, turning on the LED 6 indicates the next break will be coming soon (in 4 minutes or less).

**Comment by mgouline** [comment]
Thinking about the implementation with multiple LEDs, I have serious doubts that states will be distinguishable. Much less by someone approaching your desk from any distance. By the same token, you're welcome to try implementing it and contributing to the project :)

Most likely #4 will have to go in first -- you could put the Pomodoro stuff in a separate tab.
