### ISSUE TITLE
macOS (10.14.2) application is not recognizing the luxaforus://  URL scheme

### ISSUE THREAD

**Issue by joshfriend** [traversals/luxaforus#24]
I approved the slack integration and was taken to this page:

![](https://i.imgur.com/gr16vlr.png)

I clicked the "Open Luxaforus" button with the app already running and nothing happened. I looked at the javascript code for what the button does and crafted the `luxaforus://slack/activate?code=...` url myself and pasted it safari which said:

> macOS doesn't recognize internet addresses starting with "luxaforus:"

It seems to be registered [in the plist](https://github.com/traversals/luxaforus/blob/master/Luxaforus/Info.plist#L32), but it is just not actually working.

**Comment by mgouline** [comment]
@joshfriend Appears to work fine for me on macOS 10.14.3 in Chrome and Safari. Are you installing Luxaforus in the Applications directory or just running it from wherever you extracted it?

**Comment by joshfriend** [comment]
I did move it to the Applications folder after downloading it and before starting it

**Comment by mgouline** [comment]
Not sure then, I can't reproduce on either of the two Macs that I have access to. Seems like a random occurrence, so maybe try the usual troubleshooting: delete and reinstall the app, reboot your machine, etc.

**Comment by joshfriend** [comment]
I've tried both of those things and it still doesn't work.

Can you confirm that the correct place for downloading the app is this link? https://luxafor.com/download/

The help screen says version 1.2.30 which seems to line up with the latest tag in the repo here of v1.2.3:

![](https://i.imgur.com/dllrdqK.png)

The macOS menubar does not look anything like the screenshot on [your website here](https://traversal.space/luxaforus/), this is what i see instead:

![](https://i.imgur.com/vLGcJjs.png)

I also saw that in 25d0bde47febe01a3c805c4af3682bacae803a13 there were NSMenu items added for starting the slack integration process, but my version of the app does not have any menu items at all.

I also noticed that AppDelegate does not implement `application(_:open:options:)` so IDK how the `luxafor://` urls are supposed to work anyways: https://developer.apple.com/documentation/uikit/core_app/allowing_apps_and_websites_to_link_to_your_content/defining_a_custom_url_scheme_for_your_app

**Comment by joshfriend** [comment]
The download link on the ["How it works"](https://luxafor.com/how-it-works/) page points to an old version just FYI

**Comment by joshfriend** [comment]
I finally realized that the app on the luxafor website is different from this one, sorry for wasting your time 😓
