### ISSUE TITLE
Light turns off when screensaver turns on

### ISSUE THREAD

**Issue by amaisano** [traversals/luxaforus#25]
Is this expected behavior? Is there a way to always have it on, even when screen is locked / on saver mode?

**Comment by mgouline** [comment]
Yep, that's intended behaviour. It's assuming that when your screensaver is on, you're not at your computer and therefore neither 'available' nor 'busy'. 

There is currently no way to change that behaviour, but feel free to submit a PR to make it configurable - it shouldn't be difficult to do.
